version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.config:ro

  reactdocker: 
    build: .
    volumes:
      - ./:/Backend
    environment:
       - PORT=4000


