version: "3.8"

services:
  reactdocker: 
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes: 
      - ./:/Backend
      - /Backend/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev